schema_version = "1.0.0"

id = "Xromm_Tools"
version = "0.9.91"
name = "XROMM toolkit"
tagline = "XROMM toolkit for Blender"
maintainer = "Peter Falkingham <pfalkingham@googlemail.com>"
type = "add-on"

# Optional link to documentation, support, source files, etc
 website = "https://github.com/pfalkingham/XROMM_BlenderTools"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Pipeline"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# Optional: required by some licenses.
 copyright = [
   "2023-2025 Peter Falkingham",
 ]

# [permissions]
 files = "Import/export data"
 clipboard = "Copy and paste data"